swagger: "2.0"
info:
  description: |
    НСИ
  version: "1.0.0"
  title: NSI API
basePath: /v1
schemes:
  - http
paths:
  /nsi/meta/dict/list:
    post:
      tags:
        - meta
      summary:  ""
      description: "Получить список коротких описаний справочников"
      operationId: metaDictList
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            properties:
              metaDictListReq:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
      responses:
        200:
          description: ""
          schema:
            properties:
              metaDictListRes:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                  data:
                    type: array
                    items:
                      $ref: "#/definitions/MetaDictRef"
        500:
          description: ""
          schema:
            $ref: "#/definitions/Result"

  /nsi/meta/dict/get:
    post:
      tags:
        - meta
      summary:  ""
      description: "Получить полное описание справочника"
      operationId: metaDictGet
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            properties:
              metaDictGetReq:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                  name:
                    description: "Название словаря"
                    type: string
      responses:
        200:
          description: ""
          schema:
            properties:
              metaDictGetRes:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                  data:
                    $ref: "#/definitions/MetaDict"
        500:
          description: ""
          schema:
            $ref: "#/definitions/Result"

  /nsi/dict/count:
    post:
      tags:
        - dict
      summary:  "Получить количество записей справочника соответствующих заданному условию"
      description: ""
      operationId: dictCount
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            properties:
              dictCountReq:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                    description: "Request identifier"
                  parent:
                    description: "Ссылка на родителя в иерархии"
                    $ref: "#/definitions/DictRowAttr"
                  owner:
                    description: "Ссылка на владельца"
                    $ref: "#/definitions/DictRowAttr"
                  filter:
                    description: "Условие, которому должны соответствовать записи"
                    $ref: "#/definitions/BoolExp"
      responses:
        200:
          description: ""
          schema:
            properties:
              dictCountRes:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                  count:
                    type: integer
                    description: "Количество найденых записей"
        500:
          description: ""
          schema:
            $ref: "#/definitions/Result"

  /nsi/dict/list:
    post:
      tags:
        - dict
      summary:  "Получить страницу списка записей справочника соответствующих заданному условию"
      description: ""
      operationId: dictList
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            properties:
              dictListReq:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                  objectType:
                    description: "Тип представления объекта: ref | table определяет какой набор атрибутов будет в результате запроса"
                    type: string
                  offset:
                    type: integer
                    description: "Смещение относительно начала выборки"
                  size:
                    type: integer
                    description: "Число запрашиваемых объектов"
                  parent:
                    description: "Если справочник иерархический и мы хотим выбрать непосредственных потомков то надо задать этот параметр"
                    $ref: "#/definitions/DictRowAttr"
                  owner:
                    description: "Если справочник иерархический и мы хотим посмотреть только записи принадлежащие заданному объекту"
                    $ref: "#/definitions/DictRowAttr"
                  filter:
                    description: "Условие"
                    $ref: "#/definitions/BoolExp"
                  sort:
                    type: array
                    description: "Список условий для сортировки"
                    items:
                      $ref: "#/definitions/SortExp"
      responses:
        200:
          description: ""
          schema:
            properties:
              dictListRes:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                  data:
                    type: array
                    items:
                      $ref: "#/definitions/DictRow"
        500:
          description: ""
          schema:
            $ref: "#/definitions/Result"

  /nsi/dict/get:
    post:
      tags:
        - dict
      summary:  "Получить полное состояние строки справочника, со всеми атрибутами"
      description: ""
      operationId: dictGet
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            properties:
              dictGetReq:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                    description: "Request identifier"
                  id:
                    description: "Идентификатор записи"
                    $ref: "#/definitions/DictRowAttr"
      responses:
        200:
          description: ""
          schema:
            properties:
              dictGetRes:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                  data:
                    $ref: "#/definitions/DictRow"
        500:
          description: ""
          schema:
            $ref: "#/definitions/Result"

  /nsi/dict/save:
    post:
      tags:
        - dict
      summary:  "Сохранить состояние записи справочника, если ид атрибут задан то обновление, если нет то создание"
      description: ""
      operationId: dictSave
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            properties:
              dictSaveReq:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                    description: "Request identifier"
                  data:
                    $ref: "#/definitions/DictRow"
      responses:
        200:
          description: "Возвращаем полное состояние записи справочника"
          schema:
            properties:
              dictSaveRes:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                    description: "Request identifier"
                  data:
                    $ref: "#/definitions/DictRow"
        500:
          description: ""
          schema:
            $ref: "#/definitions/Result"

  /nsi/dict/delete:
    post:
      tags:
        - dict
      summary:  "Изменить отметку о удалении для заданной записи справочника"
      description: ""
      operationId: dictDelete
      consumes:
        - application/json
        - application/xml
      produces:
        - application/json
        - application/xml
      parameters:
        - in: body
          name: body
          description: ""
          required: true
          schema:
            properties:
              dictDeleteReq:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                    description: "Request identifier"
                  id:
                    description: "Идентификатор записи"
                    $ref: "#/definitions/DictRowAttr"
                  value:
                    type: boolean
      responses:
        200:
          description: ""
          schema:
            properties:
              dictDeleteRes:
                type: object
                properties:
                  requestId:
                    type: string
                    format: guid
                  data:
                    $ref: "#/definitions/DictRow"
        500:
          description: ""
          schema:
            $ref: "#/definitions/Result"

definitions:
  MetaDictRef:
    description: "Краткое описание справочника"
    properties:
      name:
        description: "Уникальное наименование справочника"
        type: string
      caption:
        description: "Заголовок справочника для интерфейса"
        type: string
      ownerDict:
        description: "Наименование справочника владельца"
        type: string

  MetaDict:
    description: "Описание справочника"
    properties:
      name:
        description: "Уникальное наименование справочника"
        type: string
      caption:
        description: "Заголовок справочника для интерфейса"
        type: string
      table:
        description: "Имя таблицы для хранения данных"
        type: string
      fields:
        description: "Список полей таблицы"
        type: array
        items:
          $ref: "#/definitions/MetaField"
      attrs:
        description: "Список атрибутов справочника"
        type: array
        items:
          $ref: "#/definitions/MetaAttr"
      idAttr:
        description: "Наименование атрибута кторый представлет ид"
        type: string
      parentAttr:
        description: "Наименование атрибута который представляет ссылку на родителя в иерархии"
        type: string
      groupAttr:
        description: "Наименование атрибута который представляет является ли запись группой, boolean"
        type: string
      ownerAttr:
        description: "Наименование атрибута который представляет ссылку на запись родительского справочника"
        type: string
      deleteMarkAttr:
        description: "Наименование атрибута который представляет пометку о удалении, boolean"
        type: string
      lastChangeAttr:
        description: "Наименование атрибута который представляет дату время последней модификации"
        type: string
      lastUserAttr:
        description: "Наименование атрибута который представляет уникальный идентификатор пользователя последний раз менявшего запись"
        type: string
      captionAttrs:
        description: "Список наименований атрибутов кторые используются для текстового представления записи"
        type: array
        items:
          type: string
      refObjectAttrs:
        description: "Список наименований атрибутов кторые используются для короткого представления записи"
        type: array
        items:
          type: string
      tableObjectAttrs:
        description: "Список наименований атрибутов кторые используются для табличного представления записи"
        type: array
        items:
          type: string


  MetaField:
    description: "Описание поля таблицы"
    properties:
      name:
        description: "Уникальное имя поля в таблице"
        type: string
      type:
        description: "Тип поля: string | number | date-time | boolean"
        type: string
      size:
        type: integer
      precision:
        type: integer

  MetaAttr:
    description: "Описание атрибута справочника"
    properties:
      attrType:
        description: "Тип атрибута значение или ссылка: value | ref"
        type: string
      valueType:
        description: "Тип значения, используется в тех случаях когда набор полей описывает один атрибут, например адрес"
        type: string
      name:
        description: "Уникальное имя атрибута в справочнике"
        type: string
      caption:
        type: string
      fields:
        description: "Список наименований"
        type: array
        items:
          type: string
      refDict:
        type: string
      hidden:
        description: "Атрибут является скрытым"
        type: boolean

  DictRow:
    description: "Строка справочника"
    properties:
      attrs:
        type: array
        items:
          $ref: "#/definitions/DictRowAttr"

  DictRowAttr:
    description: "Значение атрибута справочника, если полей несколько то порядок значений соответствует порядку в описании атрибута в метаданных"
    properties:
      values:
        type: array
        items:
          type: string


  BoolExp:
    properties:
      key:
        type: string
        description: "Название параметрa, соответствует атрибуту справочника"
      func:
        type: string
        description: "Функция предикат: =, <=, >=, <, > или логичекое условие: and, or, notAnd, notOr"
      value:
        $ref: "#/definitions/DictRowAttr"
        description: "Значение параметра, используется для обычных предикаторв"
      expList:
        type: array
        items:
          $ref: "#/definitions/BoolExp"

  SortExp:
    properties:
      key:
        type: string
        description: "Название параметра"
      asc:
        type: boolean
        description: "Направление сортировки"

  Result:
    properties:
      code:
        description: "Код ошибки"
        type: integer
      message:
        description: "Сообщение о ошибке"
        type: string

